### ISSUE TITLE
bug: la pantalla de welcome no muestra la variable contact llamada desde angular

### ISSUE THREAD

**Issue by JeanCarlosChavarriaHughes** [JeanCarlosChavarriaHughes/sopa#3]
El commit [fb62edcb069d5bc338d96e29bbdbfe4cd5d036d7](https://github.com/JeanCarlosChavarriaHughes/sopa/commit/fb62edcb069d5bc338d96e29bbdbfe4cd5d036d7)
 tiene el inconveniente que el uso que se le da a angular en la pantalla de welcome no esta funcionando. 

Se muestra contact: {{contact}} en lugar del valor de la variable.

**Comment by bryannsi** [comment]
Cambiar en welcome.html la etiqueta **ng-controller=""** a **ng-controller="test1Controller"**
