### ISSUE TITLE
bug: despues de ingresar bien los credenciales en login, no pasa a home

### ISSUE THREAD

**Issue by JeanCarlosChavarriaHughes** [JeanCarlosChavarriaHughes/sopa#4]
El commit [fb62edcb069d5bc338d96e29bbdbfe4cd5d036d7](https://github.com/JeanCarlosChavarriaHughes/sopa/commit/fb62edcb069d5bc338d96e29bbdbfe4cd5d036d7)

no esta pasando de la pantalla de login à la pantalla de home despues de ingresar correctamente los credenciales.  (Metodo POST)
Tal y como lo hacia en http://still-fjord-75965.herokuapp.com/public/view/login.html?

**Comment by JeanCarlosChavarriaHughes** [comment]
El problema es que todos los direccionamientos estan mal.

el directorio root del proyecto esta por encima de public. Cuando haga cualquier include de css, shared, etc tiene que empezar por el root.

/public/shared/search.html
en lugar de 
/shared/search.html

igual para los css, debe de arreglar todos los html en los que tengan includes o direccionamientos a otros archivos o referencia.

**Comment by bryannsi** [comment]
Cambiar  **app.use("/public", express.static(__dirname + '/public'));** 
a **app.use(express.static('public'));** evita tener que modificar todas las rutas de los archivos html.

**Comment by JeanCarlosChavarriaHughes** [comment]
Asegurarse que el resto de las paginas cargan bien todos los elementos. 
Probar en el servidor para estar seguro
 imagineing.ddns.net:8112
